/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.vues.InterfacesGraphiques;

import Gestion.Licence.Testlicence;
import Gestion.utils.FiltreFichier;
import Gestion.utils.JecalculeLesJours;
import java.awt.Color;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.json.simple.JSONObject;

/**
 *
 * @author christian
 */
public class ControleLicence extends javax.swing.JFrame{
    private JSONObject parametres;
    private JSONObject parametresBD;
    private int nbrejour;
    private final String nomFichier = "Documents/Licence/licence.properties";
    private boolean continuer = false;
    private boolean essaiflag = false;
    private JFileChooser selectioneur;
    private FiltreFichier filtre;
    private ConfigurateDataBase conf;
    private boolean demarage;
    private boolean licenceCorrect;
    /**
     * Creates new form ControleLicence
     */
    public ControleLicence(boolean demarage) {
        initComponents();
        this.licenceCorrect = false;
        this.demarage = demarage;
        this.setIconImage(new ImageIcon("Documents/Images/logo.png").getImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.filtre = new FiltreFichier();
        this.filtre.addFiltre(".fkc","LICENCE FILE");
        this.selectioneur = new JFileChooser("Documents/Licence");
        this.selectioneur.setFileFilter(filtre);
        this.setTitle("Entrez la licence du logiciel");
        parametres = new JSONObject();
        nbrejour = 0;
        parametresBD = Gestion.utils.Utils.provider("Documents/parametres/paramBD.properties");
        if(this.demarage){
            if(Gestion.utils.Utils.modificationBD(parametresBD,true)){
                setParam();
                testDate();
            }else{
                conf = new ConfigurateDataBase(this,true,true);
                conf.setVisible(true);
                if(conf.testconnection()){
                    setParam();
                    testDate();            
                }
            }
        }else{
            setParam();
            essai.setEnabled(false);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cotainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chemin = new javax.swing.JTextField();
        parcourir = new javax.swing.JToggleButton();
        essai = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        message = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verification");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Licence");

        parcourir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        parcourir.setText("...");
        parcourir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcourirActionPerformed(evt);
            }
        });

        essai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Info.png"))); // NOI18N
        essai.setText("Version d'essai");
        essai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        essai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                essaiActionPerformed(evt);
            }
        });

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Ok.png"))); // NOI18N
        valider.setText("Valider");
        valider.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Cancel.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Help.png"))); // NOI18N
        jButton4.setText("Contacter l'auteur");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        message.setEditable(false);
        message.setBackground(new java.awt.Color(204, 204, 204));
        message.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        message.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        message.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout cotainerLayout = new javax.swing.GroupLayout(cotainer);
        cotainer.setLayout(cotainerLayout);
        cotainerLayout.setHorizontalGroup(
            cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cotainerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(essai, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cotainerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))))
            .addGroup(cotainerLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        cotainerLayout.setVerticalGroup(
            cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cotainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(essai, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cotainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cotainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcourirActionPerformed
       boutonparcourir();
    }//GEN-LAST:event_parcourirActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        boutonAnnuler();
    }//GEN-LAST:event_annulerActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        boutonValider();
    }//GEN-LAST:event_validerActionPerformed

    private void essaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_essaiActionPerformed
        boutonEssai();
    }//GEN-LAST:event_essaiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boutonAuter();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleLicence(true);
            }
        });
    }
    
    private void setParam(){
        parametres = Gestion.utils.Utils.provider(nomFichier);
    }
    
    private void afficheMessa(int n){
        switch(n){
            case 0 :{
                message.setForeground(Color.green);
                message.setText("Licence Valide Merci !!!");
                valider.setText("continuer");
                essai.setEnabled(false);
                parcourir.setEnabled(false);
                continuer = true;     
            }
            break;
            case 1:{
                message.setForeground(Color.orange);
                message.setText("il vous reste "+nbrejour+" jours");
                essaiflag = true;
                essai.setText("poursuivre");
                parcourir.setEnabled(false);
                valider.setEnabled(false);
            }
            break;
            case 2:{
                message.setForeground(Color.red);
                message.setText("Contactez L'auteur : Periode d'essai expirée !!!");
                essai.setEnabled(false);
            }
            break;
            case 3:{
                message.setForeground(Color.red);
                message.setText("Licence invalide Merci de contacter l'auteur");
            }
            break;
        }
    }
    
    private boolean verifier(){
        boolean flag = false;
        if(parametres.get("licence").equals("KANA_FODOUP_SINDA(KFS)")){
            afficheMessa(0);
        }else{
            try {
                Date d1 = new Date(parametres.get("date1").toString());
                Date d2 = new Date(Gestion.utils.Utils.getDateActueloder());
                JecalculeLesJours je = new JecalculeLesJours();
                nbrejour = je.nbrejoursAll(d1, d2);
                int test = Gestion.utils.Utils.ObjectToInt(parametres.get("jours"));
                if(nbrejour<0 || nbrejour>test || (d2.compareTo(d1)<0)) afficheMessa(2);
                else {
                    nbrejour = test - nbrejour;
                    afficheMessa(1);
                    flag = true;
                }
            } catch (Exception ex) {
                Gestion.utils.Utils.addMessage(ex.toString(),true);
            }
        }
        return flag;
    }
    
    public boolean getLicenceCorect(){
        return this.licenceCorrect;
    }
    
    private void testDate(){
        if(parametres.get("licence").toString().equals("KANA_FODOUP_SINDA(KFS)")){
            this.licenceCorrect = true;
            new PageDeLogin().setVisible(true);
        }else{
            try {
                int n = Gestion.utils.Utils.ObjectToInt(parametres.get("deja"));
                if(n==0){
                    parametres.put("date1",Gestion.utils.Utils.getDateActueloder());
                    parametres.put("deja","1");
                    Gestion.utils.Utils.setparam(nomFichier, parametres);
                    setParam();
                }
            } catch (Exception ex) {
                Gestion.utils.Utils.addMessage(ex.toString(),true); 
            }
            this.setVisible(true);
        }
    }
    
    private void testvalider(){
        boolean flag = false;
        if(!chemin.getText().isEmpty()){
            flag = Testlicence.testValide(chemin.getText());
        }
        if(flag){
            parametres.put("licence","KANA_FODOUP_SINDA(KFS)");
            this.licenceCorrect = true;
            Gestion.utils.Utils.setparam(nomFichier, parametres);
            setParam();
            afficheMessa(0);
        }else{
            afficheMessa(3);
        }
    }
    
    private void boutonValider(){
        if(continuer){
            this.setVisible(false);
            if(demarage) new PageDeLogin().setVisible(true);
        }else{
            testvalider();
        }
    }
    
    private void boutonEssai(){
        if(essaiflag){
            this.setVisible(false);
           new PageDeLogin().setVisible(true);
        }else{
           verifier(); 
        }
    }
    
    private void boutonAuter(){
        new ViewAuteurs(this, true).setVisible(true);
    }
    
    private void boutonAnnuler(){
        if(demarage) System.exit(0);
        else this.setVisible(false);
    }
    
    private void boutonparcourir(){
       if(selectioneur.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
           File f = selectioneur.getSelectedFile();
           if(selectioneur.accept(f)){
               chemin.setText(f.getAbsolutePath());
           }
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JTextField chemin;
    private javax.swing.JPanel cotainer;
    private javax.swing.JButton essai;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField message;
    private javax.swing.JToggleButton parcourir;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
