/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.vues.InterfacesGraphiques;

import Gestion.controllers.ClassMetiers.CategorieMetier;
import Gestion.controllers.ClassMetiers.FournisseurMetier;
import Gestion.controllers.ClassMetiers.GcategorieMetier;
import Gestion.controllers.ClassMetiers.ProduitMetier;
import Gestion.passerelle.Passerelle;
import Gestion.vues.Messages.LesDonnees;
import java.util.Date;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.freixas.jcalendar.JCalendarCombo;
import org.json.simple.JSONObject;

/**
 *
 * @author christian
 */
public class GesProduits extends javax.swing.JFrame {
    private SaveFournisseur savefour;
    private SaveCategories saveCateg;
    private SaveSousCategories savesCateg;
    private ProduitMetier produit;
    private CategorieMetier categorie;
    private FournisseurMetier fournisseur;
    private JSONObject requette;
    private JSONObject message;
    private JSONObject retour;
    private Passerelle passerelle;
    boolean peutSupprimer;
    private final String[] titres = {"CODE","Designation","Fournisseur","Categorie","Sous-categorie","Prix unitaire d'achat","Prix unitaire de vente","quantite","Seuil De Vente"};
    /**
     * Creates new form GesProduits
     */
    public GesProduits() {
        initComponents();
        placerlesDonnees();
        placerscategorie();
        produit = new ProduitMetier();
        placerTableau(LesDonnees.lesproduits);
        peutSupprimer = false;
        jButton2.setEnabled(false);
        ((JCalendarCombo)dateP).setDate(new Date());
        testQTE.setSelected(false);
    }

    public JPanel getContainer(){
        return this.container;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        testQTE = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        qte = new javax.swing.JTextField();
        puv = new javax.swing.JTextField();
        designation = new javax.swing.JTextField();
        pua = new javax.swing.JTextField();
        listeFournisseurs = new javax.swing.JComboBox();
        listeCategorie = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        dateP = new org.freixas.jcalendar.JCalendarCombo();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        listeSousCategorie = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        limiteInf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textToSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Cancel.png"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Ok.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Clipboard.png"))); // NOI18N
        jButton4.setText("New");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        testQTE.setText("Quantite > ou = 0");
        testQTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testQTEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testQTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(testQTE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Designation");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PU Achat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("PU Vente (Discutable)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Quantite");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Fournisseur");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Date d'Enregistrement");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Categorie");

        listeFournisseurs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listeCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeCategorieActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Create.png"))); // NOI18N
        jButton5.setToolTipText("Ajouter ou modifier un fournisseur");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Create.png"))); // NOI18N
        jButton6.setToolTipText("Ajouter ou modifier une catégorie");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CODE");

        code.setEditable(false);
        code.setBackground(new java.awt.Color(204, 255, 255));
        code.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Create.png"))); // NOI18N
        jButton7.setToolTipText("Ajouter ou modifier une sous-catégorie");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Limite Inferieure");

        limiteInf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limiteInf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listeFournisseurs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listeCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listeSousCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pua, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(designation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dateP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(puv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limiteInf)))
                        .addGap(2, 2, 2)))
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limiteInf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listeFournisseurs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(listeCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeSousCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Designation");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Search.png"))); // NOI18N
        jButton1.setText("Filtrer");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CODE");

        text2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textToSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        savefour = new SaveFournisseur(this,true);
        savefour.setVisible(true);
        if(savefour.isaPuSauvegarder()){
            LesDonnees.initData(3);
            LesDonnees.initData(1);
            placerlesDonneesSpecial();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        saveCateg = new SaveCategories(this,true);
        saveCateg.setVisible(true);
        if(saveCateg.isaPusauvegarder()){
            LesDonnees.initData(2);
            LesDonnees.initData(1);
            placerlesDonneesSpecial();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PagePrincipale.AfficherMessage("Message",0);
        save();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PagePrincipale.AfficherMessage("Message",0);
        supprimer();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauMouseClicked
        PagePrincipale.AfficherMessage("Message",0);
        actionTableau();
    }//GEN-LAST:event_tableauMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PagePrincipale.AfficherMessage("Message",0);
        recherche();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PagePrincipale.AfficherMessage("Message",0);
        init();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            savesCateg = new SaveSousCategories(this,true,(Gestion.controllers.ClassMetiers.GcategorieMetier)Gestion.vues.Messages.LesDonnees.lesGcategories.get(listeCategorie.getSelectedItem()));
            savesCateg.setVisible(true);
            if(savesCateg.isaPusauvegarder()){
                placerscategorie();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Creer une categorie !!! ou selectionnez une categorie !!!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void listeCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeCategorieActionPerformed
        placerscategorie();
    }//GEN-LAST:event_listeCategorieActionPerformed

    private void testQTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testQTEMouseClicked
        LesDonnees.QteZero = testQTE.isSelected();
        LesDonnees.initData(1);
    }//GEN-LAST:event_testQTEMouseClicked

    private void placerlesDonnees(){
        Set fournisseurs = LesDonnees.lesfournisseurs.keySet();
        Set categories = LesDonnees.lesGcategories.keySet();
        listeFournisseurs.setModel(new javax.swing.DefaultComboBoxModel(fournisseurs.toArray()));
        listeCategorie.setModel(new javax.swing.DefaultComboBoxModel(categories.toArray()));
        code.setText(Gestion.utils.DataUtils.getCode());
    }
    
    private void placerlesDonneesSpecial(){
        Set fournisseurs = LesDonnees.lesfournisseurs.keySet();
        Set categories = LesDonnees.lesGcategories.keySet();
        listeFournisseurs.setModel(new javax.swing.DefaultComboBoxModel(fournisseurs.toArray()));
        listeCategorie.setModel(new javax.swing.DefaultComboBoxModel(categories.toArray()));
    }
    
    private void placerscategorie(){
        if(listeCategorie.getModel().getSize()!=0){
            LesDonnees.setLescategories(((Gestion.controllers.ClassMetiers.GcategorieMetier)Gestion.vues.Messages.LesDonnees.lesGcategories.get(listeCategorie.getSelectedItem())).getIdGcategorie());
//            LesDonnees.setLesSous_categories();
            Set scategories = LesDonnees.lescategories.keySet();
            listeSousCategorie.setModel(new javax.swing.DefaultComboBoxModel(scategories.toArray()));
        }
    }
    
    private void initAllData(String[] data){
        designation.setText(data[0]);
        pua.setText(data[1]);
        puv.setText(data[2]);
        qte.setText(data[3]);
        dateP.setSelectedItem(data[4]);
        listeFournisseurs.setSelectedItem(data[5]);
        listeCategorie.setSelectedItem(data[6]);
        listeSousCategorie.setSelectedItem(data[8]);
        code.setText(data[7]);
        limiteInf.setText(data[9]);
    }
    
    private void init(){
        code.setText(Gestion.utils.DataUtils.getCode());
        designation.setText("");
        pua.setText("");
        puv.setText("");
        qte.setText("");
        limiteInf.setText("");
        ((JCalendarCombo)dateP).setDate(new Date());
    }
    
    private boolean testVide(){
        boolean flag = true;
        if(designation.getText().isEmpty()){
            PagePrincipale.AfficherMessage("La designation doit etre non null !!!",2);
        }else{
            if(pua.getText().isEmpty()){
                PagePrincipale.AfficherMessage("Le prix unitaire d'achat doit etre non null !!!",2);
            }else{
                if(puv.getText().isEmpty()){
                    PagePrincipale.AfficherMessage("Le prix unitaire de vente doit etre non null !!!",2);
                }else{
                    if(qte.getText().isEmpty()){
                        PagePrincipale.AfficherMessage("La quatite en stock doit etre non null !!!",2);
                    }else{
                        if(listeSousCategorie.getModel().getSize()==0){
                            PagePrincipale.AfficherMessage("la sous categorie doit etre non null !!!",2);
                        }else{
                            if(limiteInf.getText().isEmpty()){
                                PagePrincipale.AfficherMessage("la valeur seuil doit etre non null !!!",2);
                            }else{
                                flag = false;
                            }
                        }
                    }
                }
            }
        }
        return flag;
    }
    
    private boolean testNombre(){
        boolean flag = false;
        int test = 0;
        try {
            int n = Gestion.utils.Utils.ObjectToInt(pua.getText());
            if(n<=0){
                PagePrincipale.AfficherMessage("le prix unitaire d'achat est un nombre strictement positif !!!",2);
                test++;
            }
        } catch (Exception ex) {
            PagePrincipale.AfficherMessage("le prix unitaire d'achat est un nombre !!!",2);
            test++;
        }
        try {
            int n1 = Gestion.utils.Utils.ObjectToInt(puv.getText());
            if(n1<=0){
                PagePrincipale.AfficherMessage("le prix unitaire de vente est un nombre strictement positif !!!",2);
                test++;
            }
        } catch (Exception ex) {
            PagePrincipale.AfficherMessage("le prix unitaire de vente est un nombre !!!",2);
            test++;
        }
        try {
            int n2 = Gestion.utils.Utils.ObjectToInt(qte.getText());
            if(n2<=0){
                PagePrincipale.AfficherMessage("la quantite est un nombre strictement positif !!!",2);
                test++;
            }
        } catch (Exception ex) {
            PagePrincipale.AfficherMessage("la quatite est un nombre !!!",2);
            test++;
        }
        try {
            int n3 = Gestion.utils.Utils.ObjectToInt(limiteInf.getText());
            if(n3<=0){
                PagePrincipale.AfficherMessage("la valeur seuil est un nombre strictement positif !!!",2);
                test++;
            }
        } catch (Exception ex) {
            PagePrincipale.AfficherMessage("la valeur seuil est un nombre !!!",2);
            test++;
        }
        if(test==0) flag = true;
        return flag;
    }
    
    private void save(){
        if(!testVide()){
            if(testNombre()){
                message = new JSONObject();
                requette = new JSONObject();
                fournisseur = (FournisseurMetier) LesDonnees.lesfournisseurs.get(listeFournisseurs.getSelectedItem());
                categorie = (CategorieMetier) LesDonnees.lescategories.get(listeSousCategorie.getSelectedItem());
                produit.setCode(code.getText());
                produit.setDesignation(designation.getText());
                produit.setPrix_d_achat(Integer.parseInt(pua.getText()));
                produit.setQuantite(Integer.parseInt(qte.getText()));
                produit.setSeiulLimite(Integer.parseInt(limiteInf.getText()));
                produit.setPrix_unitaire_de_vente(Integer.parseInt(puv.getText()));
                produit.setDate_de_peremtion((Date)Gestion.utils.Utils.getDate(dateP,1));
                int[] ids = new int[1];
                ids[0] = categorie.getIdcategorie();
                produit.setIdDescategories(ids);
                int[] ids1 = new int[1];
                ids1[0] = fournisseur.getIdfournisseur();
                produit.setIdDesfournisseurs(ids1);
                message.put("1",produit);
                requette.put("message",message);
                requette.put("user",PageDeLogin.currentUser);
                if(peutSupprimer) requette.put("action",7);
                else requette.put("action",6);
                passerelle = new Passerelle(requette);
                retour = passerelle.ForwardQuery();
                if(retour.get("code").equals("0")){
                    PagePrincipale.AfficherMessage(Gestion.vues.Messages.MessagePasserelle.success_ajoutproduit,1);
                    LesDonnees.initData(1);
                    LesDonnees.initData(2);
                    LesDonnees.initData(3);
                    LesDonnees.initData(5);
                    String[] data = new String[10];
                    data[0] = "";
                    data[1] = "";
                    data[2] = "";
                    data[3] = "";
                    data[4] = (new JCalendarCombo()).getSelectedItem().toString();
                    data[5] = listeFournisseurs.getSelectedItem().toString();
                    data[6] = listeSousCategorie.getSelectedItem().toString();
                    data[7] = Gestion.utils.DataUtils.getCode();
                    data[8] = listeCategorie.getSelectedItem().toString();
                    data[9] = "";
                    initAllData(data);
                    produit = new ProduitMetier();
                    peutSupprimer = false;
                    placerTableau(LesDonnees.lesproduits);
                }else{
                    PagePrincipale.AfficherMessage(Gestion.vues.Messages.MessagePasserelle.erreur_ajoutproduit,3);
                }
            }
        }
    }
    
    private void placerTableau(JSONObject data){
        Set cle = data.keySet();
        Object[][] donnee = new Object[data.size()][titres.length];
        // {"code","Designation","Fournisseur","Categorie","scategorie","Prix unitaire d'achat","quantite"};
        int i = 0;
        String condition,order; int action;
        JSONObject json;
        for (Iterator iterator = cle.iterator(); iterator.hasNext();) {
            Object next = iterator.next();
            condition = "idfournisseur="+((ProduitMetier)data.get(next)).getIdDesfournisseurs()[0];
            order = "nom asc";
            action = 23;
            json = LesDonnees.getobjet(condition, order, action);
            donnee[i][0] = ((ProduitMetier)data.get(next)).getCode();
            donnee[i][1] = ((ProduitMetier)data.get(next)).getDesignation();
            donnee[i][2] = ((FournisseurMetier)json.get("message")).getNom();
            condition = "idCategories="+((ProduitMetier)data.get(next)).getIdDescategories()[0];
            order = "designation asc";
            action = 27;
            json = LesDonnees.getobjet(condition, order, action);
            donnee[i][4] = ((CategorieMetier)json.get("message")).getDesignation();
            condition = "idGrandeCategorie="+((CategorieMetier)json.get("message")).getIdGcategories();
            order = "nom asc";
            action = 43;
            json = LesDonnees.getobjet(condition, order, action);
            donnee[i][3] = ((GcategorieMetier)json.get("message")).getNom();
            donnee[i][5] = ((ProduitMetier)data.get(next)).getPrix_d_achat();
            donnee[i][6] = ((ProduitMetier)data.get(next)).getPrix_unitaire_de_vente();
            donnee[i][7] = ((ProduitMetier)data.get(next)).getQuantite();
            donnee[i][8] = ((ProduitMetier)data.get(next)).getSeiulLimite();
            i++;
        }
        tableau.setModel(new javax.swing.table.DefaultTableModel(donnee,titres));
    }
    
    private void actionTableau(){
        int n = tableau.getSelectedRow();
        String[] data = new String[10];
        produit = (ProduitMetier)LesDonnees.lesproduits.get(tableau.getValueAt(n, 0)+" --- "+tableau.getValueAt(n, 1));
        if((produit == null || produit.getQuantite()<=0) && !testQTE.isSelected()){
           PagePrincipale.AfficherMessage("LE Produit sélectionné a une Quantité = 0 il n'est plus en stock !",3); 
        }else{
            data[7] = tableau.getValueAt(n, 0).toString();
            data[0] = tableau.getValueAt(n, 1).toString();
            data[1] = tableau.getValueAt(n, 5).toString();
            data[2] = tableau.getValueAt(n, 6).toString();
            data[3] = tableau.getValueAt(n, 7).toString();
            data[4] = (String) Gestion.utils.Utils.getDate(produit.getDate_de_peremtion(), 2);
            data[5] = tableau.getValueAt(n, 2).toString();
            data[6] = tableau.getValueAt(n, 3).toString();
            data[8] = tableau.getValueAt(n, 4).toString();
            data[9] = tableau.getValueAt(n, 8).toString();
            peutSupprimer = true;
            initAllData(data);
        }
    }
    
    private void supprimer(){
        if(peutSupprimer){
            message = new JSONObject();
            requette = new JSONObject();
            message.put("1",produit);
            requette.put("message",message);
            requette.put("user",PageDeLogin.currentUser);
            requette.put("action",12);
            passerelle = new Passerelle(requette);
            retour = passerelle.ForwardQuery();
            if(retour.get("code").equals("0")){
                PagePrincipale.AfficherMessage(Gestion.vues.Messages.MessagePasserelle.success_supprimerproduit,1);
                produit = new ProduitMetier();
                peutSupprimer = false;
                LesDonnees.initData(1);
                placerTableau(LesDonnees.lesproduits);
            }else{
                PagePrincipale.AfficherMessage(Gestion.vues.Messages.MessagePasserelle.erreur_supprimerproduit,3);
            }
        }else{
            PagePrincipale.AfficherMessage("Selectionner dans le tableau le produit a supprimer",2);
        }
    }
    
    private void recherche(){
        String m = textToSearch.getText();
        String m1 = text2.getText();
        JSONObject data = LesDonnees.getManyObjet(12,"(designation like('%"+m+"%') AND code like('%"+m1+"%'))","designation asc");
        if(data.get("code").equals("0")){
           if(((JSONObject)data.get("message")).isEmpty()){
               PagePrincipale.AfficherMessage("Pas de resultats",2);
               placerTableau(((JSONObject)data.get("message")));
            }else{
               placerTableau(((JSONObject)data.get("message")));
           }
        }else{
            PagePrincipale.AfficherMessage(Gestion.vues.Messages.MessagePasserelle.erreur_listerproduit,3);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox dateP;
    private javax.swing.JTextField designation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField limiteInf;
    private javax.swing.JComboBox listeCategorie;
    private javax.swing.JComboBox listeFournisseurs;
    private javax.swing.JComboBox listeSousCategorie;
    private javax.swing.JTextField pua;
    private javax.swing.JTextField puv;
    private javax.swing.JTextField qte;
    private javax.swing.JTable tableau;
    private javax.swing.JCheckBox testQTE;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField textToSearch;
    // End of variables declaration//GEN-END:variables
}
