package Gestion.vues.InterfacesGraphiques;

import Gestion.controllers.ClassMetiers.ClientMetier;
import Gestion.controllers.ClassMetiers.ProduitMetier;
import Gestion.passerelle.Passerelle;
import Gestion.vues.Messages.LesDonnees;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.json.simple.JSONObject;

/**
 *
 * @author FKC-Standard
 */
public class PermuterArticles extends javax.swing.JFrame {
    
    private ProduitMetier produit_Last,produit_New;
    private JSONObject Lmessage,requete,retour;
    private Passerelle passerelle;
    private ClientMetier Lclient;
    private String numFacture;
    
    public PermuterArticles() {
        initComponents();
        init();
    }
    
    public JPanel getContainer(){
        return this.contener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contener = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codeA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        designA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        puaA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        puvA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateEA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        catA = new javax.swing.JTextField();
        scatA = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        client = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pvr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        montant = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        vendeur = new javax.swing.JTextField();
        revente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        codeN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        designN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        puaN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        puvN = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dateEN = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        catN = new javax.swing.JTextField();
        scatN = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ancien Produit Vendu"));

        jLabel1.setText("Code");

        codeA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Designation");

        designA.setEditable(false);
        designA.setBackground(new java.awt.Color(255, 255, 204));
        designA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        designA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("PU Achat");

        puaA.setEditable(false);
        puaA.setBackground(new java.awt.Color(255, 255, 204));
        puaA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        puaA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("PU Vente");

        puvA.setEditable(false);
        puvA.setBackground(new java.awt.Color(255, 255, 204));
        puvA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        puvA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Date Enreg");

        dateEA.setEditable(false);
        dateEA.setBackground(new java.awt.Color(255, 255, 204));
        dateEA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateEA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Categorie");

        jLabel8.setText("Sous-Categorie");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Charger");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        catA.setEditable(false);
        catA.setBackground(new java.awt.Color(255, 255, 204));
        catA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        catA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        scatA.setEditable(false);
        scatA.setBackground(new java.awt.Color(255, 255, 204));
        scatA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        scatA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catA)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(codeA, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(designA)
                    .addComponent(puaA)
                    .addComponent(puvA)
                    .addComponent(dateEA)
                    .addComponent(scatA))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(codeA, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designA, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puaA, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puvA, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateEA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(catA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scatA, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametres d'echange"));

        jLabel15.setText("Client");

        client.setEditable(false);
        client.setBackground(new java.awt.Color(255, 255, 204));
        client.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        client.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("PV Réel");

        pvr.setEditable(false);
        pvr.setBackground(new java.awt.Color(255, 255, 204));
        pvr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pvr.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setText("Date de Vente");

        dateV.setEditable(false);
        dateV.setBackground(new java.awt.Color(255, 255, 204));
        dateV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateV.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Somme Ajoutée");

        montant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("Remarques");

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jLabel12.setText("Vendeur");

        vendeur.setEditable(false);
        vendeur.setBackground(new java.awt.Color(255, 255, 204));
        vendeur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vendeur.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        revente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        revente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Valeur de revente");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Conseil");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(client)
                    .addComponent(pvr)
                    .addComponent(dateV)
                    .addComponent(montant)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(vendeur)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(revente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(client, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pvr, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateV, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vendeur, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(revente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Nouveau produit vendu"));

        jLabel16.setText("Code");

        codeN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codeN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setText("Designation");

        designN.setEditable(false);
        designN.setBackground(new java.awt.Color(204, 255, 204));
        designN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        designN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setText("PU Achat");

        puaN.setEditable(false);
        puaN.setBackground(new java.awt.Color(204, 255, 204));
        puaN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        puaN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setText("PU Vente");

        puvN.setEditable(false);
        puvN.setBackground(new java.awt.Color(204, 255, 204));
        puvN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        puvN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setText("Date Enreg");

        dateEN.setEditable(false);
        dateEN.setBackground(new java.awt.Color(204, 255, 204));
        dateEN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateEN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setText("Categorie");

        jLabel22.setText("Sous-Categorie");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Charger");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        catN.setEditable(false);
        catN.setBackground(new java.awt.Color(204, 255, 204));
        catN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        catN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        scatN.setEditable(false);
        scatN.setBackground(new java.awt.Color(204, 255, 204));
        scatN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        scatN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catN)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(codeN, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addComponent(designN)
                    .addComponent(puaN)
                    .addComponent(puvN)
                    .addComponent(dateEN)
                    .addComponent(scatN))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(codeN, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designN, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puaN, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puvN, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateEN, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(catN, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scatN, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel12);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Cancel.png"))); // NOI18N
        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/Images/Icons/Ok.png"))); // NOI18N
        jButton6.setText("Valider");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);

        javax.swing.GroupLayout contenerLayout = new javax.swing.GroupLayout(contener);
        contener.setLayout(contenerLayout);
        contenerLayout.setHorizontalGroup(
            contenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        contenerLayout.setVerticalGroup(
            contenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       init();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        effectuer_les_echange();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        chercher(true,codeA.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        chercher(false,codeN.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Conseil();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void init(){
        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Message",0);
        codeA.setText("");
        codeN.setText("");
        designA.setText("");
        designN.setText("");
        puaA.setText("");
        puaN.setText("");
        puvA.setText("");
        puvN.setText("");
        dateEA.setText("");
        dateEN.setText("");
        catA.setText("");
        catN.setText("");
        scatA.setText("");
        scatN.setText("");
        client.setText("");
        pvr.setText("");
        dateV.setText("");
        montant.setText("");
        desc.setText("");
        vendeur.setText("");
        revente.setText("");
        numFacture = "";
        produit_Last = new ProduitMetier();
        produit_New = new ProduitMetier();
        Lclient = new ClientMetier();
    }
    
    private void chercher(boolean last,String code){
        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Message",0);
        JSONObject data = Gestion.utils.DataUtils.getproduitToChange(last,code);
        if(last){
            if(data.isEmpty()) Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Code incorrect ou"
                    + " produit non vendu ou inexistant !!!",3);
            else{
                codeA.setText(data.get("codeP").toString());
                designA.setText(data.get("designation").toString());
                puaA.setText(data.get("pua").toString());
                puvA.setText(data.get("puv").toString());
                dateEA.setText(data.get("DateE").toString());
                catA.setText(data.get("cat").toString());
                scatA.setText(data.get("scat").toString());
                client.setText(data.get("Nclient").toString());
                pvr.setText(data.get("pvr").toString());
                dateV.setText(data.get("dateV").toString());
                vendeur.setText(data.get("Nvendeur").toString());
                
                numFacture = Gestion.utils.Utils.mettreSous6Positions(""+data.get("numFac").toString());
                Lclient.setIdclient((int) data.get("cleClient"));
                Lclient.setIdAdresse((int) data.get("adC"));
                Lclient.setNom(data.get("Ncl").toString());
                Lclient.setPrenom(data.get("Pcl").toString());
                produit_Last.setIdproduit((int) data.get("cleP"));
                produit_Last.setCode(data.get("codeP").toString());
                produit_Last.setDate_de_peremtion((Date) data.get("DateE"));
                produit_Last.setDesignation(data.get("designation").toString());
                int[] idcat = {(int)data.get("idCat")};
                produit_Last.setIdDescategories(idcat);
                int[] idfour = {(int)data.get("four")};
                produit_Last.setIdDesfournisseurs(idfour);
                produit_Last.setPrix_d_achat((int)data.get("pua"));
                produit_Last.setPrix_unitaire_de_vente((int)data.get("puv"));
                produit_Last.setQuantite(((int)data.get("qte"))+1);
                produit_Last.setSeiulLimite((int)data.get("seuil"));
            }
        }else{
            if(data.isEmpty()) Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Code incorrect ou"
                    + " Produit deja vendu ou inexistant !!!",3);
            else{
                codeN.setText(data.get("codeP").toString());
                designN.setText(data.get("designation").toString());
                puaN.setText(data.get("pua").toString());
                puvN.setText(data.get("puv").toString());
                dateEN.setText(data.get("DateE").toString());
                catN.setText(data.get("cat").toString());
                scatN.setText(data.get("scat").toString());
                
                produit_New.setIdproduit((int) data.get("cleP"));
                produit_New.setIdproduit((int) data.get("cleP"));
                produit_New.setCode(data.get("codeP").toString());
                produit_New.setDate_de_peremtion((Date) data.get("DateE"));
                produit_New.setDesignation(data.get("designation").toString());
                int[] idcat = {(int)data.get("idCat")};
                produit_New.setIdDescategories(idcat);
                int[] idfour = {(int)data.get("four")};
                produit_New.setIdDesfournisseurs(idfour);
                produit_New.setPrix_d_achat((int)data.get("pua"));
                produit_New.setPrix_unitaire_de_vente((int)data.get("puv"));
                produit_New.setQuantite((int)data.get("qte"));
                produit_New.setSeiulLimite((int)data.get("seuil"));
            }
        }
    }
    
    private boolean controleValeur(){
        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Message",0);
        boolean flag = false;
        try{
            int n = Integer.parseInt(montant.getText());
            int m = Integer.parseInt(revente.getText());
            flag = (n>=0 && m>0);
        }catch(Exception e){}
        return flag;
    }
    
    private boolean controleRevente(){
        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Message",0);
        boolean flag = false;
        try{
            int m = Integer.parseInt(revente.getText());
            flag = (m>0);
        }catch(Exception e){}
        return flag;
    }
    
    private boolean controleProduit(){
        return (!designA.getText().isEmpty() && !designN.getText().isEmpty());
    }
    
    private void effectuer_les_echange(){
        if(controleProduit()){
            if(controleValeur()){
                produit_Last.setSeiulLimite(Integer.parseInt(revente.getText()));
                produit_Last.setPrix_unitaire_de_vente(Integer.parseInt(revente.getText())+5000);
                requete = new JSONObject();
                Lmessage = new JSONObject();
                Lmessage.put("1",produit_Last);
                requete.put("message",Lmessage);
                requete.put("user",PageDeLogin.currentUser);
                requete.put("action",7);
                passerelle = new Passerelle(requete);
                retour = passerelle.ForwardQuery();
                if(retour.get("code").equals("0")){
                    Lmessage = new JSONObject();
                    JSONObject lesProduits = new JSONObject();
                    String remises = desc.getText()+"\n"
                            + "Echange du produit "+produit_Last.getCode()+" contenu dans la vente Numero: "+numFacture+" par le produit "+produit_New.getCode()+" Effectué"
                            + " par l'utilisateur "+PageDeLogin.currentUser.getNom()+" "+PageDeLogin.currentUser.getPrenom();
                    String prixV=""+(Integer.parseInt(revente.getText())+Integer.parseInt(montant.getText()));
                    lesProduits.put(0+"--1--"+prixV+"--vente--"+montant.getText()+"--"+remises, produit_New);
                    Lmessage.put("lesproduits",lesProduits);
                    Lmessage.put("client",Lclient);
                    requete = new JSONObject();
                    requete.put("message",Lmessage);
                    requete.put("user",PageDeLogin.currentUser);
                    requete.put("action",9);
                    passerelle = new Passerelle(requete);
                    retour = passerelle.ForwardQuery();
                    if(retour.get("code").equals("0")){
                        init();
                        LesDonnees.initData(1);
                        LesDonnees.initData(6);
                        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Succes d'échange de produit !!!",1);
                    }else{
                        Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Erreur de vente du nouveau produit !!!",3);
                    }
                }else{
                    Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Erreur de mise à jour de l'ancien produit !!!",3);
                }
            }else{
                Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("La somme ajoutée et le montant de revente sont des valeurs entières et positives !!!",3);
            }
        }else{
            Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Charger les deux produits à échanger !!!",3);
        }
    }
    
    private void Conseil(){
        if(controleProduit()){
            if(controleRevente()){
                String m = "";
                int n = produit_New.getSeiulLimite()-Integer.parseInt(revente.getText());
                n = Math.max(0, n);
                JOptionPane.showMessageDialog(null,"Mr/Mme "+client.getText()+" doit vous ajouter un minimum de "+n+" "
                        + ""+Gestion.utils.Utils.provider("Documents/parametres/param.properties").get("unite_Monaie").toString());
            }else{
                Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Entre une extimation du montant de revente (Entiée positif) !!!",3);
            }
        }else{
            Gestion.vues.InterfacesGraphiques.PagePrincipale.AfficherMessage("Charger les deux produits à échanger !!!",3);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField catA;
    private javax.swing.JTextField catN;
    private javax.swing.JTextField client;
    private javax.swing.JTextField codeA;
    private javax.swing.JTextField codeN;
    private javax.swing.JPanel contener;
    private javax.swing.JTextField dateEA;
    private javax.swing.JTextField dateEN;
    private javax.swing.JTextField dateV;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField designA;
    private javax.swing.JTextField designN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JTextField message1;
    private javax.swing.JTextField montant;
    private javax.swing.JTextField puaA;
    private javax.swing.JTextField puaN;
    private javax.swing.JTextField puvA;
    private javax.swing.JTextField puvN;
    private javax.swing.JTextField pvr;
    private javax.swing.JTextField revente;
    private javax.swing.JTextField scatA;
    private javax.swing.JTextField scatN;
    private javax.swing.JTextField vendeur;
    // End of variables declaration//GEN-END:variables
}
